export default condtions = {
    "thunderstorm with light rain": 20,
    "thunderstorm with rain": 25,
    "thunderstorm with heavy rain": 30,
    "light thunderstorm": 15,
    "thunderstorm": 20,
    "heavy thunderstorm": 30,
    "ragged thunderstorm": 25,
    "thunderstorm with light drizzle": 15,
    "thunderstorm with drizzle": 20,
    "thunderstorm with heavy drizzle": 25,
    "light intensity drizzle": 10,
    "drizzle": 15,
    "heavy intensity drizzle": 20,
    "light intensity drizzle rain": 15,
    "drizzle rain": 20,
    "heavy intensity drizzle rain": 25,
    "shower rain and drizzle": 20,
    "heavy shower rain and drizzle": 25,
    "shower drizzle": 15,
    "light rain": 10,
    "moderate rain": 15,
    "heavy intensity rain": 20,
    "very heavy rain": 25,
    "extreme rain": 30,
    "freezing rain": 30,
    "light intensity shower rain": 15,
    "shower rain": 20,
    "heavy intensity shower rain": 25,
    "ragged shower rain": 20,
    "light snow": 20,
    "snow": 25,
    "heavy snow": 30,
    "sleet": 25,
    "light shower sleet": 20,
    "shower sleet": 25,
    "light rain and snow": 20,
    "rain and snow": 25,
    "light shower snow": 20,
    "shower snow": 25,
    "heavy shower snow": 30,
    "mist": 10,
    "smoke": 5,
    "haze": 10,
    "sand/dust whirls": 15,
    "fog": 20,
    "sand": 20,
    "dust": 20,
    "volcanic ash": 30,
    "squalls": 25,
    "tornado": 50
};  